import {
  BookOpen,
  Layers,
  Scissors,
  Zap,
  Lock,
  Unlock,
  RotateCw,
  Type,
  Hash,
  Tags,
  FileText,
  ArrowUpDown,
  PenTool,
  Wrench,
  ImagePlus,
  FileImage,
  Palette,
  Images,
  Globe,
} from 'lucide-react'
import { Tool } from './types'

export const toolsData: Tool[] = [
  {
    id: 'open-pdf',
    title: 'Open PDF',
    desc: 'Fast in-browser PDF reader with zoom controls, page jumping, thumbnail sidebar, print, and full-screen view.',
    icon: BookOpen,
    implemented: true,
    path: '/open-pdf',
    category: 'Edit',
    color: 'text-emerald-600 dark:text-emerald-400',
    bg: 'bg-emerald-50 dark:bg-emerald-950/40',
  },
  {
    id: 'merge',
    title: 'Merge PDF',
    desc: 'Combine multiple PDF files into one document.',
    icon: Layers,
    implemented: true,
    path: '/merge',
    category: 'Edit',
    color: 'text-rose-500',
    bg: 'bg-rose-50 dark:bg-rose-900/20',
  },
  {
    id: 'split',
    title: 'Split PDF',
    desc: 'Visually extract specific pages or ranges.',
    icon: Scissors,
    implemented: true,
    path: '/split',
    category: 'Edit',
    color: 'text-blue-500',
    bg: 'bg-blue-50 dark:bg-blue-900/20',
  },
  {
    id: 'compress',
    title: 'Compress PDF',
    desc: 'Optimize your file size for easier sharing.',
    icon: Zap,
    implemented: true,
    path: '/compress',
    category: 'Optimize',
    color: 'text-amber-500',
    bg: 'bg-amber-50 dark:bg-amber-900/20',
  },
  {
    id: 'protect',
    title: 'Protect PDF',
    desc: 'Secure your documents with strong encryption.',
    icon: Lock,
    implemented: true,
    path: '/protect',
    category: 'Secure',
    color: 'text-indigo-500',
    bg: 'bg-indigo-50 dark:bg-indigo-900/20',
  },
  {
    id: 'unlock',
    title: 'Unlock PDF',
    desc: 'Remove passwords from your protected files.',
    icon: Unlock,
    implemented: true,
    path: '/unlock',
    category: 'Secure',
    color: 'text-violet-500',
    bg: 'bg-violet-50 dark:bg-violet-900/20',
  },
  {
    id: 'rotate-pdf',
    title: 'Rotate PDF',
    desc: 'Fix page orientation permanently.',
    icon: RotateCw,
    implemented: true,
    path: '/rotate-pdf',
    category: 'Edit',
    color: 'text-orange-500',
    bg: 'bg-orange-50 dark:bg-orange-900/20',
  },
  {
    id: 'rearrange-pdf',
    title: 'Rearrange PDF',
    desc: 'Drag and drop pages to reorder them.',
    icon: ArrowUpDown,
    implemented: true,
    path: '/rearrange-pdf',
    category: 'Edit',
    color: 'text-emerald-500',
    bg: 'bg-emerald-50 dark:bg-emerald-900/20',
  },
  {
    id: 'page-numbers',
    title: 'Page Numbers',
    desc: 'Add numbering to your documents automatically.',
    icon: Hash,
    implemented: true,
    path: '/page-numbers',
    category: 'Edit',
    color: 'text-sky-500',
    bg: 'bg-sky-50 dark:bg-sky-900/20',
  },
  {
    id: 'watermark',
    title: 'Watermark',
    desc: 'Overlay custom text for branding or security.',
    icon: Type,
    implemented: true,
    path: '/watermark',
    category: 'Edit',
    color: 'text-purple-500',
    bg: 'bg-purple-50 dark:bg-purple-900/20',
  },
  {
    id: 'metadata',
    title: 'Metadata',
    desc: 'Edit document properties for better privacy.',
    icon: Tags,
    implemented: true,
    path: '/metadata',
    category: 'Secure',
    color: 'text-cyan-500',
    bg: 'bg-cyan-50 dark:bg-cyan-900/20',
  },
  {
    id: 'signature',
    title: 'Signature',
    desc: 'Add your electronic signature to any document.',
    icon: PenTool,
    implemented: true,
    path: '/signature',
    category: 'Edit',
    color: 'text-pink-500',
    bg: 'bg-pink-50 dark:bg-pink-900/20',
  },
  {
    id: 'grayscale',
    title: 'Grayscale',
    desc: 'Convert all document pages to black and white.',
    icon: Palette,
    implemented: true,
    path: '/grayscale',
    category: 'Optimize',
    color: 'text-zinc-500',
    bg: 'bg-zinc-50 dark:bg-zinc-900/20',
  },
  {
    id: 'pdf-to-image',
    title: 'PDF to PNG',
    desc: 'Convert document pages into high-resolution PNG images.',
    icon: FileImage,
    implemented: true,
    path: '/pdf-to-image',
    category: 'Convert',
    color: 'text-lime-500',
    bg: 'bg-lime-50 dark:bg-lime-900/20',
  },
  {
    id: 'image-to-pdf',
    title: 'Image to PDF',
    desc: 'Convert JPG, PNG, and WebP into a professional PDF.',
    icon: ImagePlus,
    implemented: true,
    path: '/image-to-pdf',
    category: 'Convert',
    color: 'text-teal-500',
    bg: 'bg-teal-50 dark:bg-teal-900/20',
  },
  {
    id: 'extract-images',
    title: 'Extract Images',
    desc: 'Pull out all original images embedded in a PDF.',
    icon: Images,
    implemented: true,
    path: '/extract-images',
    category: 'Convert',
    color: 'text-yellow-500',
    bg: 'bg-yellow-50 dark:bg-yellow-900/20',
  },
  {
    id: 'pdf-to-text',
    title: 'PDF to Text',
    desc: 'Extract plain text from your PDF documents.',
    icon: FileText,
    implemented: true,
    path: '/pdf-to-text',
    category: 'Convert',
    color: 'text-blue-600',
    bg: 'bg-blue-100 dark:bg-blue-900/20',
  },
  {
    id: 'html-to-pdf',
    title: 'HTML to PDF',
    desc: 'Convert websites, web pages, and HTML documents into PDF.',
    icon: Globe,
    implemented: true,
    path: '/html-to-pdf',
    category: 'Convert',
    color: 'text-indigo-600',
    bg: 'bg-indigo-50 dark:bg-indigo-900/20',
  },
  {
    id: 'repair',
    title: 'Repair PDF',
    desc: 'Attempt to fix corrupted or unreadable documents.',
    icon: Wrench,
    implemented: true,
    path: '/repair',
    category: 'Optimize',
    color: 'text-red-500',
    bg: 'bg-red-50 dark:bg-red-900/20',
  },
]
